POST http://localhost:8080/payments
Content-Type: application/json
Accept: application/json

{
  "requestId": 1,
  "value": "101 PLN"
}

###

GET http://localhost:8080/payments/22c61fd9-af0b-44b9-83f4-8d4df6d7383e
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/payments/started?pageNumber=0&pageSize=2
Content-Type: application/json
Accept: application/json
